/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libndkqsp_jni_NDKLib */

#ifndef _Included_org_libndkqsp_jni_NDKLib
#define _Included_org_libndkqsp_jni_NDKLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_QSPInit
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPDeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_QSPDeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsInCallBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsInCallBack
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPEnableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_QSPEnableDebugMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCurStateData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetCurStateData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCompiledDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetCompiledDateTime
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetFullRefreshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetFullRefreshCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetQstFullPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetQstFullPath
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetCurLoc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetCurLoc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetExprValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetExprValue
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetMainDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetMainDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsMainDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsMainDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarsDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetVarsDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsVarsDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsVarsDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarValuesCount
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetVarValuesCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarValues
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetVarValues
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetMaxVarsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetMaxVarsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetVarNameByIndex
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetVarNameByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetInputStrText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSetInputStrText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetActionsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetActionsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetActionData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetActionData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecuteSelActionCode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecuteSelActionCode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetSelActionIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSetSelActionIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetSelActionIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetSelActionIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsActionsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsActionsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetObjectData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetObjectData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetObjectsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetObjectsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSetSelObjectIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSetSelObjectIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetSelObjectIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetSelObjectIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPIsObjectsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPIsObjectsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecString
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecLocationCode
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecLocationCode
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecCounter
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecCounter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPExecUserInput
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPExecUserInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetLastErrorData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetLastErrorData
  (JNIEnv *, jobject);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPGetErrorDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libndkqsp_jni_NDKLib_QSPGetErrorDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPLoadGameWorld
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPLoadGameWorld
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPLoadGameWorldFromData
 * Signature: ([BLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPLoadGameWorldFromData
  (JNIEnv *, jobject, jbyteArray, jstring);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSaveGame
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSaveGame
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSaveGameAsData
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSaveGameAsData
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPOpenSavedGame
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPOpenSavedGame
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPOpenSavedGameFromData
 * Signature: ([BIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPOpenSavedGameFromData
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPRestartGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libndkqsp_jni_NDKLib_QSPRestartGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libndkqsp_jni_NDKLib
 * Method:    QSPSelectMenuItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libndkqsp_jni_NDKLib_QSPSelectMenuItem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
