/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libsnxqsp_jni_SNXLib */

#ifndef _Included_org_libsnxqsp_jni_SNXLib
#define _Included_org_libsnxqsp_jni_SNXLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPInit
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPDeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPDeInit
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPIsInCallBack
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPIsInCallBack
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPEnableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPEnableDebugMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetCurStateData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetCurStateData
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetCompiledDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetCompiledDateTime
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetFullRefreshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetFullRefreshCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetQstFullPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetQstFullPath
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetCurLoc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetCurLoc
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetExprValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetExprValue
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetMainDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetMainDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPIsMainDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPIsMainDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetVarsDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetVarsDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    isVarsDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_isVarsDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetVarValuesCount
 * Signature: (Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetVarValuesCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetVarValues
 * Signature: (Ljava/lang/String;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetVarValues
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetMaxVarsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetMaxVarsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetVarNameByIndex
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetVarNameByIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSetInputStrText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSetInputStrText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetActionsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetActionsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetActionData
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetActionData
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPExecuteSelActionCode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPExecuteSelActionCode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSetSelActionIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSetSelActionIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetSelActionIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetSelActionIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPIsActionsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPIsActionsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetObjectData
 * Signature: (I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetObjectData
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetObjectsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetObjectsCount
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSetSelObjectIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSetSelObjectIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetSelObjectIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetSelObjectIndex
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPIsObjectsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPIsObjectsChanged
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPExecString
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPExecString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPExecLocationCode
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPExecLocationCode
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPExecCounter
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPExecCounter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPExecUserInput
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPExecUserInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetLastErrorData
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetLastErrorData
  (JNIEnv *, jobject);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPGetErrorDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPGetErrorDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPLoadGameWorld
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPLoadGameWorld
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPLoadGameWorldFromData
 * Signature: ([BILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPLoadGameWorldFromData
  (JNIEnv *, jobject, jbyteArray, jint, jstring);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSaveGame
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSaveGame
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSaveGameAsData
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSaveGameAsData
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPOpenSavedGame
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPOpenSavedGame
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPOpenSavedGameFromData
 * Signature: ([BIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPOpenSavedGameFromData
  (JNIEnv *, jobject, jbyteArray, jint, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPRestartGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPRestartGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_libsnxqsp_jni_SNXLib
 * Method:    QSPSelectMenuItem
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libsnxqsp_jni_SNXLib_QSPSelectMenuItem
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
